### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by skt-t1-byungi** [skt-t1-byungi/clearall#1]

**Comment by goldenthumb** [comment]
https://github.com/skt-t1-byungi/clearall/blob/06b067b76da7245c2f714160ce3df1eca5dbaa76/index.ts#L46-L49

좋은 방법이네요~ 근데 굳이 이렇게 할 필요가 있을까요? unsubscribe 라는 걸 알려주기 위한 용도인건지 궁금합니다. 

그리고 개인적으로 좀 더 범용적으로 사용하기 위해서는 특정 이벤트만 제거 하는 로직도 필요할 것 같은데 차라리 add 할 때 마다 각각 clear 하는 함수를 return 해주고 clearAll 을 별도로 제공해주는 건 어떨까요?
